<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <material name="green">
        <color rgba="0 0.6 0 1" />
    </material>

  <material name="silver">
    <color rgba="0.8 0.8 0.8 1.0"/>
  </material>
    <material name="gray">
        <color rgba="0.7 0.7 0.7 1" />
    </material>

    <material name = "black">
        <color rgba="0 0 0 1"/>
    </material>

    <xacro:macro name="box_inertia" params="m x y z o_xyz o_rpy">
        <inertial>
            <mass value="${m}" />
            <origin xyz="${o_xyz}" rpy="${o_rpy}" />
            <inertia ixx="${(m/12) * (z*z + y*y)}" ixy="0" ixz="0"
                    iyy="${(m/12) * (x*x + z*z)}" iyz="0"
                    izz="${(m/12) * (x*x + y*y)}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r l o_xyz o_rpy">
        <inertial>
            <origin xyz="${o_xyz}" rpy="${o_rpy}" />
  <mass value="0.5"/>
            <inertia ixx="${(m/12) * (3*r*r + l*l)}" ixy="0" ixz="0"
                    iyy="${(m/12) * (3*r*r + l*l)}" iyz="0"
                    izz="${(m/2) * (r*r)}" />        </inertial>
    </xacro:macro>


    

    <xacro:macro name="sphere_inertia" params="m r o_xyz o_rpy">
        <inertial>
            <mass value="${m}" />
            <origin xyz="${o_xyz}" rpy="${o_rpy}" />
            <inertia ixx="${(2/5) * m * r * r}" ixy="0" ixz="0"
                    iyy="${(2/5) * m * r * r}" iyz="0"
                    izz="${(2/5) * m * r * r}" />
        </inertial>
    </xacro:macro>

    <xacro:macro name="camera" params="width height hfov color">
        
    <visual>
        <geometry>
            <box size="0.015 0.040 0.030" />
        </geometry>
        <material name="${color}" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </visual>
    <visual>
        <geometry>
            <cylinder radius="0.010" length="0.015"/>
        </geometry>
        <material name="green" />
        <origin xyz="0.0075 0 0" rpy="0 ${pi / 2.0} 0" />
    </visual>
    <mass value = "0.1" />
        <inertia ixx="0.000166667" iyy = "0.000166667" izz="0.000166667" />
    </xacro:macro>

   <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
                <material name="gray" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            <!-- <surface>
              <friction>
                <ode>
                  <mu1>0.8</mu1> 
                  <mu2>0.2</mu2>
                </ode>
              </friction>
            </surface> -->
            </collision>
            <fdir1 value="1 0 0"/>
            <xacro:sphere_inertia m="0.01" r="${wheel_radius}" 
                                    o_xyz="0 0 0" o_rpy="${pi / 2.0} 0 0" />
        </link>

    </xacro:macro>

    <xacro:macro name = "wheel_joint" params = "child_prefix xyz xyz_axis rpy">
        <joint name="base_${child_prefix}_wheel_joint" type="continuous">
            <parent link="base_link" />
            <child link="${child_prefix}_wheel_link" />
            <origin xyz="${xyz}" rpy="${rpy}" />
            <axis xyz="${xyz_axis}" />
        
             <!-- <dynamics damping="0.0" friction="0.0"/> -->
        </joint>

    </xacro:macro>




<xacro:macro name="robo_link" params="name radius length material mass">

  <link name="${name}">
      <visual>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
          <origin xyz="0.0 0.0 ${length/2}" rpy="0.0 0.0 0.0"/>
        <material name="${material}"/>
      </visual>
      <collision>
          <geometry>
              <cylinder length="${length}" radius="${radius}"/>
          </geometry>
          <origin xyz="0.0 0.0 ${length/2}" rpy="0.0 0.0 0.0"/>
      </collision>
      <inertial>
          <mass value="${mass}" />
          <origin xyz="0 0 0" rpy="0 0 0" />
          <inertia ixx="${(mass/12) * (3*radius*radius + length*length)}" ixy="0" ixz="0"
                  iyy="${(mass/12) * (3*radius*radius + length*length)}" iyz="0"
                  izz="${(mass/2) * (radius*radius)}" />
      </inertial>
    </link>
</xacro:macro>

<xacro:macro name = "box_link" params = "name sx sy sz material mass">

  <link name="${name}">
    <visual>
      <geometry>
      <!-- <box size="0.1 0.1 0.1"/> -->
        <mesh filename="file://$(find antr_description)/stl/excavator.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <material name="${material}"/>
    </visual>
    <collision>
      <geometry>
        <box size="${sx} ${sy} ${sz}"/>
      </geometry>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
    </collision>

  <inertial>
  <mass value="${mass}"/>
  <origin xyz="0 0 0" rpy="0 0 0" />
  <inertia ixx="${mass*(sy*sy + sz* sz)/12}" ixy="0.0" ixz="0.0" iyy="${mass*(sx*sx + sz* sz)/12}" iyz="0.0" izz="${mass*(sy*sy + sx* sx)/12}"/>
  </inertial>

  </link>

</xacro:macro>


<xacro:macro name="ros2_control_joint" params = "name mi ma">
  <joint name="${name}">

        <command_interface name = "position">
            <param name="min" value="${mi}"/>
            <param name="max" value="${ma}"/>        
        </command_interface>    

        <state_interface name = "velocity" />
        <state_interface name = "position"/>
    </joint>
</xacro:macro>

</robot>